spring:
  application:
    name: "empMgmt"
  h2:
    console:
      enabled: false
  datasource:
    url: jdbc:h2:file:D:/TERZO/db/empdb
    driverClassName: org.h2.Driver
    username: sa
    password: sa
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none

server:
  port: 9000

management:
  endpoints:
    web:
      exposure:
        include: "env"
  security:
    enabled: false
  